version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000", "9001:9001"]
    volumes: ["minio_data:/data"]

  backend:
    build: .
    depends_on: [db, minio]
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/tasks
      - MINIO_ENDPOINT=minio:9000
    ports: ["8000:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
  minio_data:
